name: Terraform AWS Infrastructure & Deployment

on:
  push:
    branches:
      - main  

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Initialize Terraform
      run: terraform init -backend=false   -chdir=terraform

    - name: Create Terraform Workspace
      run:   terraform workspace new Node.js || terraform workspace select Node.js  -chdir=terraform

    - name: Apply Terraform Configuration
      run: terraform apply -var-file="Node.js-environment.tfvars" -auto-approve -chdir=terraform
